### ISSUE TITLE
New operation: GraphResolve

### ISSUE THREAD

**Issue by redhog** [ucbepic/docetl#108]
After my first few steps of extraction, I have something along the lines of

```
[
  {"name": "Steam engine", "related_to": ["Boiler", "Turbine", "Ship", "Locomotive"]},
  {"name": "Steam boiler", "related_to": ["Turbine", "Steam engine", "Steam ship", "Locomotive"]},
  {"name": "Locomotive", "related_to": ["Steam engine", "Steam boiler", "Train", "Track"]},
]
```

As can be seen, the names listed in the `related_to` array are not always the exact same as the ones listed in `name` of the items. It'd like to somehow run a resolve operation to unify this set of names, so `related_to` links don't point out into the void!

But how can such an operation be structured in docetl? I believe this isn't possible with the current set of operations. So this is mostly a question of what new operation(s) we could add that would make this possible to solve using docetl.

**Comment by shreyashankar** [comment]
Hmm interesting. If they were all names (or stored in a name field that was exploded/unnested), resolve could at least create the distinct set of names, and somehow you'd have to wrangle the join of the names back on the `related_to`. But this is quite tedious.

I wonder if it makes sense to write a GraphResolve Operation for this, which takes in an `edge_key` (which will be a list, like `related_to`) and a `node_key` (e.g., `name` in your example), with the same interface as Resolve (without defining the output schema, since we know the unit of resolution), but the operation will make edits to the `node_key` and `edge_key` fields.

Let me think about other ideas today. I'm at the conference so my thoughts are a bit all over the place :-)

**Comment by redhog** [comment]
It's the wrangling that's a bit... hard. GraphResolve is simple, straight forward, but a bit non-generic. Could we do something like providing an operation that runsa sub-pipeline (where you'd just run resolve)?

**Comment by shreyashankar** [comment]
Wouldn't the sub-pipeline also be non-generic here?

**Comment by redhog** [comment]
The idea would be that there's a generic "split out this data and run this set of ops on it, then merge it again" operation, where the ops are configurable, and the difference from just sticking them in the main pipeline would be what items they operate on. But maybe it's overkill?

**Comment by shreyashankar** [comment]
yeah it seems like this GraphResolve use case is actually common. we don't have any operators to help create graphs
